/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AiSuggestionUpdateManyWithoutRootsInput } from "./AiSuggestionUpdateManyWithoutRootsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { ChallengeRootWhereUniqueInput } from "../../challengeRoot/base/ChallengeRootWhereUniqueInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { DictionaryEntryUpdateManyWithoutRootsInput } from "./DictionaryEntryUpdateManyWithoutRootsInput";

@InputType()
class RootUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AiSuggestionUpdateManyWithoutRootsInput,
  })
  @ValidateNested()
  @Type(() => AiSuggestionUpdateManyWithoutRootsInput)
  @IsOptional()
  @Field(() => AiSuggestionUpdateManyWithoutRootsInput, {
    nullable: true,
  })
  aiSuggestions?: AiSuggestionUpdateManyWithoutRootsInput;

  @ApiProperty({
    required: false,
    type: () => ChallengeRootWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ChallengeRootWhereUniqueInput)
  @IsOptional()
  @Field(() => ChallengeRootWhereUniqueInput, {
    nullable: true,
  })
  challenge?: ChallengeRootWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  classicalOrigin?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  creator?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DictionaryEntryUpdateManyWithoutRootsInput,
  })
  @ValidateNested()
  @Type(() => DictionaryEntryUpdateManyWithoutRootsInput)
  @IsOptional()
  @Field(() => DictionaryEntryUpdateManyWithoutRootsInput, {
    nullable: true,
  })
  entries?: DictionaryEntryUpdateManyWithoutRootsInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isCompleted?: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  notes?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  rootLetters?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  transliteration?: string | null;
}

export { RootUpdateInput as RootUpdateInput };
