/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SubmissionService } from "../submission.service";
import { SubmissionCreateInput } from "./SubmissionCreateInput";
import { Submission } from "./Submission";
import { SubmissionFindManyArgs } from "./SubmissionFindManyArgs";
import { SubmissionWhereUniqueInput } from "./SubmissionWhereUniqueInput";
import { SubmissionUpdateInput } from "./SubmissionUpdateInput";

export class SubmissionControllerBase {
  constructor(protected readonly service: SubmissionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Submission })
  async createSubmission(
    @common.Body() data: SubmissionCreateInput
  ): Promise<Submission> {
    return await this.service.createSubmission({
      data: {
        ...data,

        entry: data.entry
          ? {
              connect: data.entry,
            }
          : undefined,

        reviewer: data.reviewer
          ? {
              connect: data.reviewer,
            }
          : undefined,

        user: {
          connect: data.user,
        },
      },
      select: {
        entry: {
          select: {
            id: true,
          },
        },

        feedback: true,
        id: true,
        notes: true,
        reviewedAt: true,

        reviewer: {
          select: {
            id: true,
          },
        },

        status: true,
        submissionType: true,
        submittedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Submission] })
  @ApiNestedQuery(SubmissionFindManyArgs)
  async submissions(@common.Req() request: Request): Promise<Submission[]> {
    const args = plainToClass(SubmissionFindManyArgs, request.query);
    return this.service.submissions({
      ...args,
      select: {
        entry: {
          select: {
            id: true,
          },
        },

        feedback: true,
        id: true,
        notes: true,
        reviewedAt: true,

        reviewer: {
          select: {
            id: true,
          },
        },

        status: true,
        submissionType: true,
        submittedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Submission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async submission(
    @common.Param() params: SubmissionWhereUniqueInput
  ): Promise<Submission | null> {
    const result = await this.service.submission({
      where: params,
      select: {
        entry: {
          select: {
            id: true,
          },
        },

        feedback: true,
        id: true,
        notes: true,
        reviewedAt: true,

        reviewer: {
          select: {
            id: true,
          },
        },

        status: true,
        submissionType: true,
        submittedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Submission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSubmission(
    @common.Param() params: SubmissionWhereUniqueInput,
    @common.Body() data: SubmissionUpdateInput
  ): Promise<Submission | null> {
    try {
      return await this.service.updateSubmission({
        where: params,
        data: {
          ...data,

          entry: data.entry
            ? {
                connect: data.entry,
              }
            : undefined,

          reviewer: data.reviewer
            ? {
                connect: data.reviewer,
              }
            : undefined,

          user: {
            connect: data.user,
          },
        },
        select: {
          entry: {
            select: {
              id: true,
            },
          },

          feedback: true,
          id: true,
          notes: true,
          reviewedAt: true,

          reviewer: {
            select: {
              id: true,
            },
          },

          status: true,
          submissionType: true,
          submittedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Submission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSubmission(
    @common.Param() params: SubmissionWhereUniqueInput
  ): Promise<Submission | null> {
    try {
      return await this.service.deleteSubmission({
        where: params,
        select: {
          entry: {
            select: {
              id: true,
            },
          },

          feedback: true,
          id: true,
          notes: true,
          reviewedAt: true,

          reviewer: {
            select: {
              id: true,
            },
          },

          status: true,
          submissionType: true,
          submittedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
