/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ActivityListRelationFilter } from "../../activity/base/ActivityListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { AiSuggestionListRelationFilter } from "../../aiSuggestion/base/AiSuggestionListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { CommentListRelationFilter } from "../../comment/base/CommentListRelationFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DefinitionListRelationFilter } from "../../definition/base/DefinitionListRelationFilter";
import { ExampleListRelationFilter } from "../../example/base/ExampleListRelationFilter";
import { ExtractedWordListRelationFilter } from "../../extractedWord/base/ExtractedWordListRelationFilter";
import { IntFilter } from "../../util/IntFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { RootWhereUniqueInput } from "../../root/base/RootWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { SubmissionListRelationFilter } from "../../submission/base/SubmissionListRelationFilter";

@InputType()
class DictionaryEntryWhereInput {
  @ApiProperty({
    required: false,
    type: () => ActivityListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ActivityListRelationFilter)
  @IsOptional()
  @Field(() => ActivityListRelationFilter, {
    nullable: true,
  })
  activities?: ActivityListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AiSuggestionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AiSuggestionListRelationFilter)
  @IsOptional()
  @Field(() => AiSuggestionListRelationFilter, {
    nullable: true,
  })
  aiSuggestions?: AiSuggestionListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  approvalDate?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  approvalUser?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  audioFilePath?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CommentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CommentListRelationFilter)
  @IsOptional()
  @Field(() => CommentListRelationFilter, {
    nullable: true,
  })
  comments?: CommentListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  creator?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => DefinitionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DefinitionListRelationFilter)
  @IsOptional()
  @Field(() => DefinitionListRelationFilter, {
    nullable: true,
  })
  definitions?: DefinitionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ExampleListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExampleListRelationFilter)
  @IsOptional()
  @Field(() => ExampleListRelationFilter, {
    nullable: true,
  })
  examples?: ExampleListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ExtractedWordListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExtractedWordListRelationFilter)
  @IsOptional()
  @Field(() => ExtractedWordListRelationFilter, {
    nullable: true,
  })
  extractedWords?: ExtractedWordListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: BooleanFilter,
  })
  @Type(() => BooleanFilter)
  @IsOptional()
  @Field(() => BooleanFilter, {
    nullable: true,
  })
  isChallengeWord?: BooleanFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  lastEditor?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  originType?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  partOfSpeech?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RootWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RootWhereUniqueInput)
  @IsOptional()
  @Field(() => RootWhereUniqueInput, {
    nullable: true,
  })
  root?: RootWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  status?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => SubmissionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SubmissionListRelationFilter)
  @IsOptional()
  @Field(() => SubmissionListRelationFilter, {
    nullable: true,
  })
  submissions?: SubmissionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  transliteration?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  verbForm?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  word?: StringFilter;
}

export { DictionaryEntryWhereInput as DictionaryEntryWhereInput };
