/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ExampleService } from "../example.service";
import { ExampleCreateInput } from "./ExampleCreateInput";
import { Example } from "./Example";
import { ExampleFindManyArgs } from "./ExampleFindManyArgs";
import { ExampleWhereUniqueInput } from "./ExampleWhereUniqueInput";
import { ExampleUpdateInput } from "./ExampleUpdateInput";

export class ExampleControllerBase {
  constructor(protected readonly service: ExampleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Example })
  async createExample(
    @common.Body() data: ExampleCreateInput
  ): Promise<Example> {
    return await this.service.createExample({
      data: {
        ...data,

        creator: data.creator
          ? {
              connect: data.creator,
            }
          : undefined,

        entry: {
          connect: data.entry,
        },
      },
      select: {
        contextNotes: true,
        createdAt: true,

        creator: {
          select: {
            id: true,
          },
        },

        entry: {
          select: {
            id: true,
          },
        },

        exampleText: true,
        id: true,
        translation: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Example] })
  @ApiNestedQuery(ExampleFindManyArgs)
  async examples(@common.Req() request: Request): Promise<Example[]> {
    const args = plainToClass(ExampleFindManyArgs, request.query);
    return this.service.examples({
      ...args,
      select: {
        contextNotes: true,
        createdAt: true,

        creator: {
          select: {
            id: true,
          },
        },

        entry: {
          select: {
            id: true,
          },
        },

        exampleText: true,
        id: true,
        translation: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Example })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async example(
    @common.Param() params: ExampleWhereUniqueInput
  ): Promise<Example | null> {
    const result = await this.service.example({
      where: params,
      select: {
        contextNotes: true,
        createdAt: true,

        creator: {
          select: {
            id: true,
          },
        },

        entry: {
          select: {
            id: true,
          },
        },

        exampleText: true,
        id: true,
        translation: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Example })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateExample(
    @common.Param() params: ExampleWhereUniqueInput,
    @common.Body() data: ExampleUpdateInput
  ): Promise<Example | null> {
    try {
      return await this.service.updateExample({
        where: params,
        data: {
          ...data,

          creator: data.creator
            ? {
                connect: data.creator,
              }
            : undefined,

          entry: {
            connect: data.entry,
          },
        },
        select: {
          contextNotes: true,
          createdAt: true,

          creator: {
            select: {
              id: true,
            },
          },

          entry: {
            select: {
              id: true,
            },
          },

          exampleText: true,
          id: true,
          translation: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Example })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteExample(
    @common.Param() params: ExampleWhereUniqueInput
  ): Promise<Example | null> {
    try {
      return await this.service.deleteExample({
        where: params,
        select: {
          contextNotes: true,
          createdAt: true,

          creator: {
            select: {
              id: true,
            },
          },

          entry: {
            select: {
              id: true,
            },
          },

          exampleText: true,
          id: true,
          translation: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
